# Generated by Django 3.1.3 on 2020-12-02 08:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('address', models.TextField(null=True)),
            ],
            options={
                'db_table': 'db_universities',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.users')),
                ('grade', models.FloatField(default=0, null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.universities')),
            ],
            options={
                'db_table': 'db_student',
            },
            bases=('authentication.users', models.Model, object),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.users')),
                ('rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.universities')),
            ],
            options={
                'db_table': 'db_professor',
            },
            bases=('authentication.users', models.Model, object),
        ),
    ]
