# Generated by Django 3.1.3 on 2020-12-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
